### ISSUE TITLE
Request to support multi arch images for additional arm architectures

### ISSUE THREAD

**Issue by subfuzion** [dart-lang/dart-docker#11]
Issue originally created in [subfuzion/dart-docker-slim repo](https://github.com/subfuzion/dart-docker-slim). See discussion at: [#11](https://github.com/subfuzion/dart-docker-slim/issues/11)

**Comment by cpswan** [comment]
Something else to be aware of...

I had a go at automating the builds I was doing yesterday using a GitHub action like:

```yaml
name: Docker

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./platform/Dockerfile
          push: true
          tags: |
            atsigncompany/dartshowplatform:test
            atsigncompany/dartshowplatform:GHA${{ github.run_number }}
          platforms: |
            linux/amd64
            linux/arm/v7
            linux/arm64/v8
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
```

Building for `linux/arm/v7` fails like this:

```logs
#26 [linux/arm/v7 stage-0 4/4] RUN dart2native /app/platform.dart -o /app/platform
#26 sha256:8dfddb27285d806e5cebf1fb002a0c2c632fd65ccb314e3ac8499208550373d1
#26 0.506 ../../runtime/vm/cpu_arm.cc: 151: error: Unrecognized ARM CPU architecture.
#26 0.507 version=2.12.4 (stable) (Thu Apr 15 12:26:53 2021 +0200) on "linux_arm"
#26 0.508 pid=7, thread=7, isolate_group=vm-isolate(0xff7f8000), isolate=vm-isolate(0xffa04000)
#26 0.508 isolate_instructions=fea18a80, vm_instructions=fea18a80
#26 0.511   pc 0xfebb6ea9 fp 0xfd2a6a30 dart::Profiler::DumpStackTrace(void*)+0x4c
#26 0.512   pc 0xfea18b6d fp 0xfd2a6a40 dart::Assert::Fail(char const*, ...)+0x1c
#26 0.513   pc 0xfeb17e19 fp 0xfd2a6a68 dart::HostCPUFeatures::Init()+0x17c
#26 0.516   pc 0xfeb183b7 fp 0xfd2a6b78 dart::Dart::Init(unsigned char const*, unsigned char const*, _Dart_Isolate* (*)(char const*, char const*, char const*, char const*, Dart_IsolateFlags*, void*, char**), bool (*)(void**, char**), void (*)(void*, void*), void (*)(void*, void*), void (*)(void*), void (*)(), void* (*)(char const*, bool), void (*)(unsigned char**, int*, void*), void (*)(void const*, int, void*), void (*)(void*), bool (*)(unsigned char*, int), _Dart_Handle* (*)(), bool, Dart_CodeObserver*)+0x346
#26 0.517   pc 0xfeec4e59 fp 0xfd2a6bd8 Dart_Initialize+0x54
#26 0.518   pc 0xfea0a03b fp 0xfd2a6c90 dart::bin::main(int, char**)+0x2be
#26 0.519   pc 0xfea0ac9b fp 0xfd2a6ca0 main+0xa
#26 0.519 -- End of DumpStackTrace
#26 0.657 qemu: uncaught target signal 6 (Aborted) - core dumped
#26 0.925 Aborted (core dumped)
#26 ERROR: executor failed running [/bin/sh -c dart2native /app/platform.dart -o /app/platform]: exit code: 134
```

Where I think the key error message is `Unrecognized ARM CPU architecture.` coming from `dart2native` not being happy about the QEMU environment it finds itself in.

I'd note that Docker buildx normalises armhf to arm, so this shouldn't be about missing (emulated) hardware floating point support.

So what we have here is something that works on real hardware (like a Raspberry Pi), but doesn't get along with QEMU.

Whether that's Dart's fault or Docker/QEMU might be open to some debate. But raised here because this is exactly the sort of thing that people are going to try to do with multi arch images.

If I remove `linux/arm/v7` then `linux/amd64` and `linux/arm64/v8` build just fine.

In some ways it doesn't surprise my that `dart2native` struggles here, as the arm/v7 world can be a bit of a mess. On the other hand, given the myriad of Android devices and the use there of Dart/Flutter I'm surprised this hasn't come to light already.
