### ISSUE TITLE
Got 'AOT compilation failed' when 'dart compile exe'

### ISSUE THREAD

**Issue by sxd1140** [dart-lang/dart-docker#34]
Here is my Dockerfile
```
FROM dart:stable AS build

WORKDIR /app
COPY pubspec.* ./
RUN dart pub get

COPY . .
RUN dart pub get --offline
RUN dart compile -v exe bin/main.dart -o bin/server

FROM scratch
COPY --from=build /runtime/ /
COPY --from=build /app/bin/server /app/bin/

EXPOSE 8080
CMD ["/app/bin/server"]
```

I got this
```
Compiling /app/bin/main.dart to /app/bin/server using format exe:
Generating AOT kernel dill.
Error: AOT compilation failed
Generating AOT kernel dill failed!
The command '/bin/sh -c dart compile -v exe bin/main.dart -o bin/server' returned a non-zero code: 64
```

pubspec.yaml
```
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: 4.0.0
  web_socket_channel: 2.1.0
  html: 0.15.0
  puppeteer: 2.2.0
  shelf: 1.1.4
  shelf_router: 1.0.0
  shelf_static: 1.0.0
  sembast: 3.1.0+2

dev_dependencies:
  test: ^1.16.0
```

System info
```
Centos 7.4.1708 amd64
Docker version 20.10.7, build f0df350
```
